import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillGithub,
  AiFillLinkedin,
  AiFillBehanceCircle,
} from "react-icons/ai";

import Image from "next/image";
import sun from "../public/sun.png";
import design from "../public/design.png";
import code from "../public/code.png";
import ComingSoon from "../public/ComingSoon.png";

import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode? "dark": ""}>
      <Head>
        <title>Nagasundar Peddibhotla Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/sun.png" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 pb-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-mono dark:text-red-100">NagasundarP</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={()=>setDarkMode(!darkMode)}className="cursor-pointer dark:text-red-100" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-purple-500 to-red-400 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-purple-600 font-medium md:text-6xl">
              Nagasundar Peddibhotla
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-red-100">
              Frontend Developer and UI/UX designer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-red-100">
              I am a Frontend Developer and UI/UX designer. I have recently
              dipped my toes in Frontend Development and have 1+ years of
              experience in UI/UX design. I have worked on various projects and
              have a good understanding of the latest technologies. I am a quick
              learner and a team player. I am looking for a challenging role in
              a reputed organization where I can utilize my skills and knowledge
              to the fullest.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-red-100">
            <AiFillGithub />
            <AiFillLinkedin />
            {/* <AiFillBehanceCircle /> */}
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-purple-700 rounded-full w-80 h-80 mt-20 mb-10 overflow-hidden md:h-96 md:w-96">
            <Image src={sun} alt="sun" layout="fill" objectFit="cover" />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-3 text-center text-purple-500">
              Services I offer
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800"></p>
            <div className="text-center">
              <p>
                <span className="text-purple-500">UI/UX</span>
              </p>
              <p className="dark:text-red-100">Web Design</p>
              <p>
                <span className="text-purple-500">Frontend Development</span>
              </p>
              <p className="dark:text-red-100">Web Development</p>
            </div>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-red-100">
              <Image
                src={design}
                alt=""
                className="mx-auto"
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2 text-purple-500">
                UI/UX
              </h3>
              <p className="text-md py-2 leading-8 text-gray-800">
                UI/UX design is the process of creating a product that provides
                meaningful and relevant experiences to users. This involves the
                design of the interface, interaction, and experience of the
                product. Helping you to create a product that provides
                meaningful and relevant experiences to users.
                <span className="text-purple-600 p-2">
                  So lets get started.
                </span>
              </p>
              <h4 className="text-purple-500 py-2">Design tools I use</h4>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Adobe Photoshop</p>
              <p className="text-gray-800 py-1">Adobe Illustrator</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-red-100">
              <Image
                src={code}
                alt=""
                className="mx-auto"
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2 text-purple-500">
                Frontend Developer
              </h3>
              <p className="text-md py-2 leading-8 text-gray-800">
                Frontend development is the process of converting the UI/UX
                design to a functional website. This involves the development of
                the interface and the experience of the product. Building robust
                and scalable websites that are fast and responsive. User
                experience is my top priority.
                <span className="text-purple-600 p-2">
                  Website is the first impression of your business. Let&apos;s
                  make it a good one.
                </span>
              </p>
              <h4 className="text-purple-500 py-2">
                Frontend Development tools I use
              </h4>
              <p className="text-gray-800 py-1">HTML</p>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">Tailwind CSS</p>
              <p className="text-gray-800 py-1">Bootstrap</p>
              <p className="text-gray-800 py-1">Javascript</p>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">GraphQL</p>
              <p className="text-gray-800 py-1">TypeScript</p>
              <span className="text-purple-600 p-2">& more</span>
            </div>
          </div>
        </section>
        <section>
          <div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-red-100">
              <h3 className="text-3xl py-3 text-center text-purple-500">
                My Work
              </h3>
              <p className="text-md pl-2 text-center leading-8 text-gray-800">
                I have worked on various projects and have a good understanding
                of the latest technologies. Looking for new opportunities to
                work on challenging projects.
              </p>
              <div>
                <div className="text-center">
                  <Image
                    src={ComingSoon}
                    alt=""
                    className="mx-auto rounded-lg"
                    width={"100%"}
                    height={"100%"}
                  />
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
