import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillGithub,
  AiFillLinkedin,
  AiFillBehanceCircle,
} from "react-icons/ai";

import Image from "next/image";
import sun from "../public/sun.png";
import design from "../public/design.png";
import code from "../public/code.png";
import ComingSoon from "../public/ComingSoon.png";

import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode? "dark": ""}>
      <Head>
        <title>Nagasundar Peddibhotla Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/sun.png" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 pb-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-mono dark:text-red-100">NagasundarP</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={()=>setDarkMode(!darkMode)}className="cursor-pointer dark:text-red-100" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-purple-500 to-red-400 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-purple-600 font-medium md:text-6xl">
              Nagasundar Peddibhotla
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-red-100">
              Frontend Developer and UI/UX designer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-red-100">
              I am a Frontend Developer and UI/UX designer. I have recently
              dipped my toes in Frontend Development and have 1+ years of
              experience in UI/UX design. I have worked on various projects and
              have a good understanding of the latest technologies. I am a quick
              learner and a team player. I am looking for a challenging role in
              a reputed organization where I can utilize my skills and knowledge
              to the fullest.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-red-100">
            <a href="https://github.com/NagasundarP" rel="noreferrer" target="_blank"><AiFillGithub /></a>
            <a href="https://www.linkedin.com/in/nagasundar-peddibhotla-217262207/" rel="noreferrer" target="_blank"><AiFillLinkedin /></a>
            {/* <AiFillBehanceCircle /> */}
          </div>
        </section>
        <section>
          <div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-red-100">
              <h3 className="text-3xl py-3 text-center text-purple-500">
                My Work
              </h3>
              <p className="text-md pl-2 text-center leading-8 text-gray-800">
                I have worked on various projects and have a good understanding
                of the latest technologies. Looking for new opportunities to
                work on challenging projects.
              </p>
              <div>
                <div className="text-center">
                  <Image
                    src={ComingSoon}
                    alt=""
                    className="mx-auto rounded-lg"
                    width={"100%"}
                    height={"100%"}
                  />
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
